# Generated by Django 4.1.7 on 2023-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDlcGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=300)),
                ('eng_name', models.CharField(max_length=300)),
                ('eng_game', models.CharField(max_length=300)),
                ('rus_game', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cat', models.CharField(max_length=30)),
                ('pspl', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('realise', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'База дополнений',
                'verbose_name_plural': 'База дополнения',
            },
        ),
        migrations.CreateModel(
            name='BaseGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=300)),
                ('eng_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('cat', models.CharField(max_length=30)),
                ('pspl', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=200, null=True)),
                ('local', models.CharField(max_length=150, null=True)),
                ('photo', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('realise', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'База игр',
                'verbose_name_plural': 'База игр',
            },
        ),
        migrations.CreateModel(
            name='DiscountGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('eng_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('full_price', models.CharField(max_length=6)),
                ('buy_price', models.CharField(max_length=6)),
                ('cat', models.CharField(max_length=30)),
                ('pspl', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('realise', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Распродажа',
                'verbose_name_plural': 'Распродажи',
            },
        ),
        migrations.CreateModel(
            name='DlcGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('eng_name', models.CharField(max_length=300)),
                ('eng_game', models.CharField(max_length=300)),
                ('rus_game', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('full_price', models.CharField(max_length=6)),
                ('buy_price', models.CharField(max_length=6)),
                ('cat', models.CharField(max_length=30)),
                ('pspl', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('realise', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Дополнения',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('eng_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=6)),
                ('full_price', models.CharField(max_length=6)),
                ('buy_price', models.CharField(max_length=6)),
                ('cat', models.CharField(max_length=30)),
                ('pspl', models.CharField(max_length=30)),
                ('lang', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=10)),
                ('realise', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Игру',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('finish', models.CharField(max_length=100)),
                ('count_games', models.CharField(max_length=10)),
                ('count_dlc', models.CharField(max_length=10)),
                ('count_discount', models.CharField(max_length=10)),
                ('proxies', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=300)),
            ],
        ),
    ]
