# Generated by Django 4.1.7 on 2023-04-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedlcgames',
            name='lang',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basedlcgames',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basedlcgames',
            name='local',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
