# Generated by Django 4.1.7 on 2023-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_basedlcgames_lang_alter_basedlcgames_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedlcgames',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='basegames',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
